<p>Factorio is a game where your space ship crash lands on a planet and you are tasked with trying to leave.  The only life on this planet are the trees & plants and a hostile insectoid hive-mind called the "biters".  The world has a lot of resources available for you to get off, but it's all in the raw form -- iron ore, copper ore, coal and oil.  It's up to you to take those raw resources and eventually build a spaceship out of them.</p>

<p>Dyson Sphere Program (DSP) is a game where you are a robot sent to a star system and tasked to construct a Dyson Sphere; a sphere of solar panels around a star designed to capture all of the energy that it outputs.  The only life you encounter is plants and trees and the planets you visit each have their own set of raw resources -- iron ore, copper ore, coal, oil and others.  It's up to you to take those raw resources and eventually build a Dyson sphere out of them.</p>

<p>These two games play incredibly similar to each other but I found myself feeling quite differently as they progressed.</p>

<p>In Factorio the graphics are all browns and grays.  Everything feels like it has a dirty filter over it; your factory, the world, the trees, the water, the biters.  The camera is fixed from a long distance away since the main thing your attention is on is the factory you're building.  This has the effect of making you feel distanced from the world you're interacting with.</p>

<p>In DSP the graphics are very brightly coloured and you can rotate your camera freely in 3D.  You can zoom in to look yourself directly in the face and see the individual trees and flowers beside you.  You can zoom out and see the planet that you start on rotating around a gas giant that's rotating around the local star.  You can even move to other stars nearby and watch the planets lazily rolling around them.  The star system feels alive and moving.</p>

<p>As your game in Factorio progresses your factory grows bigger and better.  At first the biters don't really care about you but as you start extracting resources from the planet they begin taking notice of your actions and you'll stumble across a few nests of theirs.  If you approach these nests they'll come and attack you and as you kill them and expand they'll become more numerous and stronger.  There are an infinite number of them and as your factory continues to grow, so do they.  Eventually you'll construct your spaceship and leave and the implication is that the biters will come and destroy your factory, restoring the planet to more or less the state it was in before you arrived.</p>

<p>In DSP the first thing you need to do is cut down trees so you can power your robot suit.  As the game progresses you'll steadily destroy the trees on your planet and pave over the oceans with concrete.  Eventually the bright and vibrant world that you landed on will start to look like an airport, paved over with bright blinking lights and spinning structures everywhere.  There is nothing to oppose you and nothing to stop you.  When you're successful you will have constructed a Dyson sphere, absorbing all of the energy output of the star.  If there was ever any possibility of life recovering, the dyson sphere will have sealed that fate.  The star system is doomed to lifelessness but this is not enough!  Your next step is to fly to the next star system and do it again and again until you have extinguished all possibility of life everywhere.  In-universe humanity has retreated into a virtual world and it doesn't take much imagination to wonder why.</p>

<p>For me Factorio felt like it was an exciting game about growth.  I learned a bunch of new systems and as my factory grew bigger I grew prouder of it and wanted to show it off to my friends.  In contrast, Dyson Sphere Program felt like a game about destruction.  I took these beautiful worlds and converted them into cold lifeless resource nodes.  I felt ashamed to show off my creation to my friends because I knew what used to be there and what the eventual outcome would be.</p>

<p>Each game taken as a set of mechanics feels very good to play.  It’s very satisfying to start out on an untouched world and to slowly build up an automation empire out of the materials you find around you, to slowly build towards a penultimate goal step by step.  Factorio acted as a fantastic start into this genre but it wasn’t until I played Dyson Sphere Program that I started thinking about the bigger picture of what I was doing.</p>


